# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('key', models.CharField(db_index=True, max_length=8, unique=True)),
            ],
        ),
    ]
